import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  cratesSidebar: [{type: 'autogenerated', dirName: 'crates'}],
  itemsSidebar: [{type: 'autogenerated', dirName: 'items'}],
  starterSidebar: [{type: 'autogenerated', dirName: 'starter'}],
  contributingSidebar: [{type: 'autogenerated', dirName: 'contributing'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
